# Generated by Django 3.1.4 on 2020-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=2000)),
                ('status', models.IntegerField(choices=[(1, 'activate'), (0, 'Deactivate')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'yetkazib berivchilar',
            },
        ),
    ]
