# Generated by Django 3.1.4 on 2020-12-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
