# Generated by Django 3.1.4 on 2020-12-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1)),
                ('product_info', models.CharField(max_length=400)),
                ('product_warranty', models.CharField(max_length=200)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produktlar',
            },
        ),
    ]
