# Generated by Django 3.1.4 on 2020-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201222_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='logo',
            field=models.ImageField(max_length=200, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='static/img'),
        ),
    ]
