# Generated by Django 3.1.4 on 2020-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201218_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='view_cnt',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='sale_percent',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
