# Generated by Django 3.1.4 on 2020-12-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201218_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('size', models.FloatField()),
                ('view_cnt', models.IntegerField(blank=True, default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Produktlist',
                'verbose_name_plural': 'Produktlistlar',
            },
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
