# Generated by Django 3.1.4 on 2020-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201218_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_warranty',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
