# Generated by Django 3.1.4 on 2020-12-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brend'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.model'),
        ),
    ]
