# Generated by Django 3.1.4 on 2020-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201221_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='brend',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/img'),
        ),
    ]
